// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_wDKvRTQLQ9TUU5Sqe_3UjU08DhXK7tg',
    appId: '1:950916096154:web:8975b727dd57dc94af3f23',
    messagingSenderId: '950916096154',
    projectId: 'medicalapp-f56d9',
    authDomain: 'medicalapp-f56d9.firebaseapp.com',
    storageBucket: 'medicalapp-f56d9.firebasestorage.app',
    measurementId: 'G-H7W3Y9NGHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhvkZ-jhwLgWyK4aoAFR3w5JfCfhAnYns',
    appId: '1:950916096154:android:f862de68d1fd0fc4af3f23',
    messagingSenderId: '950916096154',
    projectId: 'medicalapp-f56d9',
    storageBucket: 'medicalapp-f56d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRvSw3aa8VTvoHQF6RoVvuDMqvYifE_wk',
    appId: '1:950916096154:ios:e8749a5abb722558af3f23',
    messagingSenderId: '950916096154',
    projectId: 'medicalapp-f56d9',
    storageBucket: 'medicalapp-f56d9.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRvSw3aa8VTvoHQF6RoVvuDMqvYifE_wk',
    appId: '1:950916096154:ios:e8749a5abb722558af3f23',
    messagingSenderId: '950916096154',
    projectId: 'medicalapp-f56d9',
    storageBucket: 'medicalapp-f56d9.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_wDKvRTQLQ9TUU5Sqe_3UjU08DhXK7tg',
    appId: '1:950916096154:web:2c2bb1ec1d5cd3a7af3f23',
    messagingSenderId: '950916096154',
    projectId: 'medicalapp-f56d9',
    authDomain: 'medicalapp-f56d9.firebaseapp.com',
    storageBucket: 'medicalapp-f56d9.firebasestorage.app',
    measurementId: 'G-V5R5Q4D09D',
  );
}
